// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe              = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact             = require("reason-react/lib/js/src/reasonReact.js");
var TodoApp$TestReasonReact = require("./TodoApp.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, TodoApp$TestReasonReact.make("todo", /* array */[])), "root");

/*  Not a pure module */
